apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-app2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-app2
    spec:
      containers:
      - name: nodejs-app2
        image: nodejs-app
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080
